PhpChallenge\Bundle\TodoBundle\Entity\TodoItem:
    type:  entity
    table: todo_item
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
    fields:
        description:
            type: string
            nullable: false
        status:
            type: string
            default: 'active'
            nullable: false
        deletedAt:
            type: date
            nullable: true
    manyToOne:
        list:
            targetEntity: PhpChallenge\Bundle\TodoBundle\Entity\TodoList
            inversedBy: items
            joinColumn:
                name: list_id
                referencedColumnName: id

