imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        connections:
            default:
                dbname: %database_name%_test
                options:
                    1002: 'SET SESSION wait_timeout=600;'

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
